default: eratosthenes

eratosthenes.o: eratosthenes.c
	gcc -c eratosthenes.c -o eratosthenes.o

eratosthenes: eratosthenes.o
	gcc erathosthenes.o -o eratosthenes

clean:
	-rm -f eratosthenes.o
	-rm -f eratosthenes
